name: Check and plan template

on: pull_request
jobs:
	init-and-plan:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v4
		- uses: hashicorp/setup-terraform@v3
		- name: Terraform fmt
			id: fmt
			run: terraform fmt -check
			continue-on-error: false

		- name: Terraform Init
			id: init
			run: terraform init

		- name: Terraform Validate
			id: validate
			run: terraform validate -no-color

		- name: Terraform Plan
			id: plan
			run: terraform plan -no-color
			continue-on-error: true